//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETDONDATHANG
    {
        public int MaCTDH { get; set; }
        public Nullable<int> MaDonHang { get; set; }
        public Nullable<int> MaDH { get; set; }
        public int MaSANPHAM { get; set; }
        public Nullable<int> MaSize { get; set; }
        public Nullable<int> Soluong { get; set; }
        public Nullable<decimal> Dongia { get; set; }
    
        public virtual DONDATHANG DONDATHANG { get; set; }
        public virtual DONHANG DONHANG { get; set; }
        public virtual SANPHAM SANPHAM { get; set; }
        public virtual SIZE SIZE { get; set; }
    }
}
