//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DANHMUC
    {
        public DANHMUC()
        {
            this.SANPHAMs = new HashSet<SANPHAM>();
        }
    
        public int MaDM { get; set; }
        public string TenDANHMUC { get; set; }
        public string meta { get; set; }
    
        public virtual ICollection<SANPHAM> SANPHAMs { get; set; }
    }
}
