//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUANGCAO
    {
        public int Id { get; set; }
        public string slider1 { get; set; }
        public string linkslider1 { get; set; }
        public string slider2 { get; set; }
        public string linkslider2 { get; set; }
        public string slider3 { get; set; }
        public string linkslider3 { get; set; }
    }
}
