//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SANPHAM
    {
        public int MaSANPHAM { get; set; }
        public string TenSANPHAM { get; set; }
        public string meta { get; set; }
        public Nullable<decimal> Giaban { get; set; }
        public string GioiThieu { get; set; }
        public string Mota { get; set; }
        public string HinhAnh { get; set; }
        public string HinhAnh1 { get; set; }
        public string HinhAnh2 { get; set; }
        public Nullable<System.DateTime> Ngaycapnhat { get; set; }
        public Nullable<int> Soluongton { get; set; }
        public Nullable<int> MaDM { get; set; }
        public Nullable<int> MaNSX { get; set; }
    
        public virtual DANHMUC DANHMUC { get; set; }
        public virtual NHASANXUAT NHASANXUAT { get; set; }
    }
}
