//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TheLoai
    {
        public TheLoai()
        {
            this.TinTucs = new HashSet<TinTuc>();
        }
    
        public int MaTheLoai { get; set; }
        public string TenTheLoai { get; set; }
        public string meta { get; set; }
    
        public virtual ICollection<TinTuc> TinTucs { get; set; }
    }
}
